export const GET_ERRORS = "GET_ERRORS";

export const GET_PROFILE = "GET_PROFILE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
